#ifndef MT_COMMAND_H
#define MT_COMMAND_H
#include <stddef.h>
typedef enum {
    COMMAND_NONE,
    COMMAND_SAVE,
    COMMAND_SELECT_ALL,
    COMMAND_COPY,
    COMMAND_CUT,
    COMMAND_PASTE,
    COMMAND_UNDO,
    COMMAND_REDO,
    COMMAND_BACKSPACE,
    COMMAND_DELETE,
    COMMAND_NEWLINE,
    COMMAND_TAB,
    COMMAND_CURSOR_LEFT,
    COMMAND_CURSOR_RIGHT,
    COMMAND_CURSOR_UP,
    COMMAND_CURSOR_DOWN,
    COMMAND_WORD_LEFT,
    COMMAND_WORD_RIGHT,
    COMMAND_LINE_START,
    COMMAND_LINE_END,
    COMMAND_BUFFER_START,
    COMMAND_BUFFER_END,
    COMMAND_KILL_LINE,
    COMMAND_ISEARCH,
    COMMAND_QUERY_REPLACE,
    COMMAND_PAGE_UP,
    COMMAND_PAGE_DOWN,
    COMMAND_EXECUTE_COMMAND,
    COMMAND_SHELL,
    COMMAND_FIND_FILE,
    COMMAND_DIRED,
    COMMAND_NEXT_BUFFER,
    COMMAND_DIRED_OPEN,
    COMMAND_DIRED_REFRESH,
    COMMAND_DIRED_CREATE_FILE,
    COMMAND_DIRED_CREATE_DIRECTORY,
    COMMAND_DIRED_RENAME,
    COMMAND_DIRED_DELETE,
    COMMAND_LIST_COMMANDS,
    COMMAND_QUIT
} Command;
const char *command_name(Command command);
Command command_from_name(const char *name);
size_t command_count(void);
const char *command_name_at(size_t index);
#endif
